# Generated by Django 4.2.1 on 2023-05-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='recommended_by',
            new_name='referred_by',
        ),
        migrations.AddField(
            model_name='profile',
            name='referral_credits',
            field=models.IntegerField(default=0),
        ),
    ]
